@startuml tictactoe


class Game {
}
Game *--> Board
Game *--> Turn

Turn --> "2" Player
Turn --> Board
class Turn {
    + next():void
    + getPlayer():Player
}

class Player {
    + put(Coordinate):void
    + move(Coordinate, Coordinate):void
    + getToken():Token
}
Player --> Board
Player --> Token
Player ..> Error
Player ..> Coordinate

class Board {
    + isValidToPut(Coordinate):Error
    + isValidToRemove(Token, Coordinate):Error
    + put(Token, Coordinate):void
    + remove(Coordinate):void
}
Board ..> Token
Board ..> Error
Board ..> Coordinate

class Coordinate {
    + random():void
    + isValid():Error
}
Coordinate ..> Error

enum Error {
    PUT
    MOVE
    NULL
}

enum Token {
    O
    X
    NULL
}

class views.console.View #pink {
    + interact():void
}
class views.console.StartView #pink {
    + interact():void
}
class views.console.PlayView #pink {
    + interact():void
}
class views.console.ResumeView #pink {
    + interact():void
}
class views.console.BoardView #pink {
    + write():void
}
class views.console.CoordinateView #pink {
    + read(String):Coordinate
}
class views.console.ErrorView #pink {
    + write():void
}
class views.console.TokenView #pink {
    + write():void
    + getSymbol():char
}
views.console.View *--> views.console.StartView
views.console.View *--> views.console.PlayView
views.console.View *--> views.console.ResumeView

views.console.PlayView *--> views.console.BoardView
views.console.PlayView ..> views.console.CoordinateView
views.console.PlayView ..> views.console.ErrorView
views.console.BoardView ..> views.console.TokenView

views.console.PlayView --> Game
views.console.StartView --> Game
views.console.ResumeView --> Game

views.console.BoardView --> Game
views.console.TokenView --> Token
views.console.ErrorView --> Error

views.console.CoordinateView ..> Coordinate

views.View --> Game

abstract class views.View #pink {
    + interact():void
    # {abstract} getStartView():void
    # {abstract} getPlayView():void
    # {abstract} isResumed():boolean
}

views.View <|-- views.console.View
views.View <|-- views.gui.View

class views.gui.View #pink {}

abstract class TicTacToe {
    # createView():View
}
TicTacToe *--> Game
TicTacToe *--> views.View

TicTacToe <|-- CLITicTacToe
TicTacToe <|-- GUITicTacToe

CLITicTacToe ..> views.console.View
GUITicTacToe ..> views.gui.View

class CLITicTacToe {
    + {static} main
}

class GUITicTacToe {
    + {static} main
}
@enduml